In [13]:
# Importanciónes y dependencias
import pandas as pd
import numpy as np
from pathlib import Path
from sqlalchemy import create_engine, text

In [14]:
# Configuraciones de rutas (pathlib resuelve conflictos rutas linux y windows)
BASE_PATH = Path().resolve()
DATA_PROCESSED = BASE_PATH / ".." / "data" / "processed"
DATA_CURATED = BASE_PATH / ".." / "data" / "curated"

DATA_CURATED.mkdir(parents=True, exist_ok=True)

file_path = DATA_PROCESSED / "nasa_exoplanets_processed.csv"

In [15]:
# Lectura del arcchivo csv rawprocessed
df = pd.read_csv(file_path)

# Informacion del dataframe
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

# Impresion de primeras filas
df.head()

Filas: 1183
Columnas: 8

,pl_name,hostname,ra,dec,sy_dist,pl_rade,pl_bmasse,pl_orbsmax
0,14 Her b,14 Her,242.602101,43.816362,17.9323,NaN,1774.193506,2.817444
1,16 Cyg B b,16 Cyg B,295.465642,50.516824,21.1397,NaN,533.514528,1.662833
2,2MASS J01225093-2439505 b,2MASS J01225093-2439505,20.712801,-24.664613,33.8281,11.209000,7786.500000,52.000000
3,2MASS J12073346-3932539 b,2MASS J12073346-3932539,181.889091,-39.548440,64.3080,15.692573,1504.285905,50.500000
4,2MASS J21252752-8138278 b,2MASS J21252752-8138278,321.366299,-81.641489,34.1154,NaN,3813.940884,7493.000000

In [16]:
# Función de clasificación basada en Radio (más confiable que masa en exoplanetas)
def classify_planet(row):
    r = row['pl_rade']
    if pd.isna(r): return 'Unknown'
    if r < 1.25: return 'Terrestre'
    if r < 2.0:  return 'Super-Tierra'
    if r < 6.0:  return 'Neptuniano'
    return 'Gigante Gaseoso'

df['planet_type'] = df.apply(classify_planet, axis=1)

df.head()

,pl_name,hostname,ra,dec,sy_dist,pl_rade,pl_bmasse,pl_orbsmax,planet_type
0,14 Her b,14 Her,242.602101,43.816362,17.9323,NaN,1774.193506,2.817444,Unknown
1,16 Cyg B b,16 Cyg B,295.465642,50.516824,21.1397,NaN,533.514528,1.662833,Unknown
2,2MASS J01225093-2439505 b,2MASS J01225093-2439505,20.712801,-24.664613,33.8281,11.209000,7786.500000,52.000000,Gigante Gaseoso
3,2MASS J12073346-3932539 b,2MASS J12073346-3932539,181.889091,-39.548440,64.3080,15.692573,1504.285905,50.500000,Gigante Gaseoso
4,2MASS J21252752-8138278 b,2MASS J21252752-8138278,321.366299,-81.641489,34.1154,NaN,3813.940884,7493.000000,Unknown

In [17]:
# Selección de columnas (sin el ID, que lo pondrá Postgres)
cols = [
    'pl_name', 'hostname', 
    'pl_rade', 'pl_bmasse', 
    'pl_orbsmax', 'sy_dist', 
    'planet_type'
]

df_planets_curated = df[cols].copy()

df_planets_curated.head()

,pl_name,hostname,pl_rade,pl_bmasse,pl_orbsmax,sy_dist,planet_type
0,14 Her b,14 Her,NaN,1774.193506,2.817444,17.9323,Unknown
1,16 Cyg B b,16 Cyg B,NaN,533.514528,1.662833,21.1397,Unknown
2,2MASS J01225093-2439505 b,2MASS J01225093-2439505,11.209000,7786.500000,52.000000,33.8281,Gigante Gaseoso
3,2MASS J12073346-3932539 b,2MASS J12073346-3932539,15.692573,1504.285905,50.500000,64.3080,Gigante Gaseoso
4,2MASS J21252752-8138278 b,2MASS J21252752-8138278,NaN,3813.940884,7493.000000,34.1154,Unknown

In [ ]:

engine = create_engine("postgresql://user:password@localhost:5432/BCSS")

# 1. Obtener los IDs actuales de la DB
df_original = pd.read_sql("SELECT nasa_exoplanet_id, pl_name FROM nasa_exoplanets", engine)

# 2. Unir con tus datos clasificados (df_planets_curated)
df_final = pd.merge(df_planets_curated, df_original, on='pl_name', how='left')

df_final.head()

,pl_name,hostname,pl_rade,pl_bmasse,pl_orbsmax,sy_dist,planet_type,nasa_exoplanet_id
0,14 Her b,14 Her,NaN,1774.193506,2.817444,17.9323,Unknown,1
1,16 Cyg B b,16 Cyg B,NaN,533.514528,1.662833,21.1397,Unknown,2
2,2MASS J01225093-2439505 b,2MASS J01225093-2439505,11.209000,7786.500000,52.000000,33.8281,Gigante Gaseoso,3
3,2MASS J12073346-3932539 b,2MASS J12073346-3932539,15.692573,1504.285905,50.500000,64.3080,Gigante Gaseoso,4
4,2MASS J21252752-8138278 b,2MASS J21252752-8138278,NaN,3813.940884,7493.000000,34.1154,Unknown,5

In [21]:
# Guardar final
output_path = DATA_CURATED / "planet_type_curated.csv"
df_final.to_csv(output_path, index=False)

print(f"Archivo NASA guardado en: {output_path}")
print(f"Resumen: {len(df_final)} planetas procesadas.")

Archivo NASA guardado en: F:\Usuario\Diego\Estudios\Ilerna\EspacializacionBigDataIA\ProyectoBigData\proyectoBCSS\notebook\..\data\curated\planet_type_curated.csv
Resumen: 1183 planetas procesadas.